name: ACTION SHELLCHECK

on:
  pull_request:
    branches: [ "main" ]

jobs:
  action-shellcheck:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: info
          format: json
