name: PYTEST

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9.8'

      - name: Test with pytest
        run: |
          pip install pytest
          pytest python/ 
