name: PYTEST

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest python/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      